### ISSUE TITLE
Compilation failures with Linux kernel 7.2 and Clang/LTO

### ISSUE THREAD

**Issue by SoftEng-Islam** [KanuX-14/rtl8188eus#21]
# Compilation failures with Linux kernel 7.2 and Clang/LTO

## Environment
- **Kernel Version:** Linux 7.2.0 (CachyOS LTO kernel)
- **Compiler:** Clang 21.1.8 with LTO enabled
- **Driver Version:** Commit b5f02e7 (2026-07-07) - "Building support for kernel 7.1.x and newer"
- **Distribution:** NixOS with CachyOS kernel
- **Architecture:** x86_64

## Issue Description

The driver fails to compile on Linux kernel 7.2 with Clang when LTO and strict error checking are enabled. While commit b5f02e7 added support for kernel 7.1.x (cfg80211 API changes), it doesn't address compilation issues with kernel 7.2's stricter compiler requirements.

### 1. Array Bounds Warnings Treated as Errors

Multiple instances of array indexing on flexible array members trigger `-Werror=array-bounds`:

```c
os_dep/linux/ioctl_linux.c:7089:50: error: array index 24 is past the end of the array (that has type 'u8[0]' (aka 'unsigned char[0]')) [-Werror,-Warray-bounds]
_rtw_memcpy(psecuritypriv->dot118021XGrprxmickey[param->u.crypt.idx].skey, &(param->u.crypt.key[24]), 8);
                                                                             ^                  ~~
././include/ieee80211.h:266:4: note: array 'key' declared here
u8 key[0];
^
```

Similar errors occur at:
- `os_dep/linux/ioctl_linux.c:7155` (index 16)
- `os_dep/linux/ioctl_linux.c:7156` (index 24)

The issue stems from `struct ieee_param` in `include/ieee80211.h` using a flexible array member:
```c
struct ieee_param {
    // ...
    union {
        struct {
            // ...
            u8 key[0];  // Flexible array member
        } crypt;
    } u;
};
```

### 2. Missing strncpy Declaration

```c
os_dep/linux/os_intfs.c:1401:2: error: call to undeclared library function 'strncpy' with type 'char *(char *, const char *, unsigned long)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
strncpy(adapter->old_ifname, dev->name, IFNAMSIZ);
^
```

### What Works
1. ✅ AppleTalk struct definitions (already included in commit b5f02e7's changes to `core/rtw_br_ext.c`)
2. ✅ Replacing `strncpy` with `strscpy` resolves the string function issue

### What Doesn't Work
Attempts to disable `-Werror=array-bounds` via:
- `EXTRA_CFLAGS += -Wno-error=array-bounds`
- `ccflags-y += -Wno-error=array-bounds`
- Environment variable `KCFLAGS`

These don't work because the CachyOS LTO kernel enforces strict compiler flags at the kbuild level that cannot be overridden by external modules.

## Root Cause

The flexible array member pattern `u8 key[0]` is a legacy C idiom that modern compilers with strict bounds checking correctly flag as undefined behavior when accessed with offsets. Kernel 7.2 with Clang/LTO enforces these checks as errors.

### Option 1: Update Flexible Array Members (Recommended)
Replace zero-length arrays with proper flexible array member syntax:
```c
// Old (problematic)
u8 key[0];

// New (C99+ standard)
u8 key[];
```

However, this may require careful review as the code accesses these arrays with hardcoded offsets (8, 16, 24), suggesting they might not be truly flexible arrays but rather fixed-size buffers misrepresented as flexible arrays.

### Option 2: Fix Array Size Declarations
If the arrays have known maximum sizes, declare them properly:
```c
#define IEEE_CRYPT_KEY_LEN 32
u8 key[IEEE_CRYPT_KEY_LEN];
```

### Option 3: Add Compiler Pragma (Workaround)
Add pragmas around problematic code sections:
```c
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Warray-bounds"
// problematic array access
#pragma GCC diagnostic pop
```

## Additional Notes

- The cfg80211 API changes for kernel 7.1+ (net_device → wireless_dev) are correctly implemented
- The issue only manifests with strict compiler configurations (Clang + LTO + -Werror)
- Standard GCC compilation without LTO may not show these errors

## Steps to Reproduce

1. Use Linux kernel 7.2 compiled with Clang and LTO
2. Enable `-Werror=array-bounds` compiler flag
3. Attempt to compile the driver with commit b5f02e7 or later
4. Observe compilation failures in `os_dep/linux/ioctl_linux.c`

## Request

Could you please address the flexible array member usage to ensure compatibility with modern compiler strictness requirements? This would enable the driver to work with cutting-edge kernel configurations using Clang/LTO.

Thank you for maintaining this driver!

**Comment by SimplyCEO** [comment]
Thanks for reporting a issue.
I am currently using a slightly older version of the kernel.
When I get to update I will research about it.
